## Importing Libraries and Setting Pandas Features

In [28]:
# import all necessary libraries
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import pandas as pd
import time
import random
import os
import re
from pathlib import Path

In [29]:
# set pandas display setting
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", None)

## Cricket Dataframe

In [30]:
# define url and headers for reference later
url = 'https://orthsoc.org/sina/cricklist.htm'
headers = {
    "User-Agent": (
        "AcademicResearchBot"
        "(collecting data for non-commercial communication signals research project)"
    ),
    "Accept": "text/html,application/xhtml+xml",
    "Accept-Language": "en-US,en;q=0.9",
    "Connection": "keep-alive"
}

In [31]:
# get code for cricket webpage
response = requests.get(url, headers = headers)
soup = BeautifulSoup(response.text, 'html.parser')

In [32]:
# retrieve species names and urls and store them in species_list
cricket_species_list = []
for species in soup.find_all("h3", class_="species"):
    a_tag = species.find("a")
    if a_tag:
        species_name = a_tag.get_text(strip = True)
        species_url = urljoin("https://orthsoc.org/sina/", a_tag["href"])
        cricket_species_list.append({"species": species_name, "url": species_url})

In [33]:
grouped_data = []
session = requests.Session()
session.headers.update(headers)

for species in cricket_species_list:
    r = session.get(species["url"], timeout=15)
    r.encoding = r.apparent_encoding
    soup = BeautifulSoup(r.text, "html.parser")

    species_name = species["species"]

    # finding range map of species (if possible)
    map_large = None
    map_figure = soup.find("table", class_="images")

    if map_figure:
        map_link = map_figure.find("a", href=True)
        if map_link:
            href = map_link["href"]

            match = re.search(r"(\d+)m\.htm", href, re.I)
            if match:
                code = match.group(1)
                href = f"{code}mc.gif"
                map_large = urljoin(species["url"], href)

    if not map_large:
        for row in soup.find_all("tr"):
            caps = row.find_all("td", class_="captions")
            for idx, cap in enumerate(caps):
                if "map" in cap.get_text(" ", strip=True).lower():
                    prev = row.find_previous_sibling("tr")
                    if not prev:
                        continue

                    imgs = prev.find_all("td", class_="images")
                    if idx >= len(imgs):
                        continue

                    link = imgs[idx].find("a", href=True)
                    if not link:
                        continue

                    href = link["href"]
                    match = re.search(r"(\d+)m\.htm", href, re.I)
                    if match:
                        code = match.group(1)
                        href = f"{code}mc.gif"
                        map_large = urljoin(species["url"], href)
                    break
            if map_large:
                break

    recording_blocks = soup.find_all(
        "div",
        class_=lambda x: x and "recording" in x
    )

    for rec in recording_blocks:

        text = rec.get_text(" ", strip=True)

        # find audio file
        audio = None
        audio_tag = rec.find("audio")
        if audio_tag:
            source = audio_tag.find("source", src=True)
            if source:
                audio = urljoin(species["url"], source["src"])

        # find spectrogram
        spectrogram = None

        for img in rec.find_all("img", src=True):
            src = img["src"].lower()
            alt = (img.get("alt") or "").lower()

            combined = f"{src} {alt} {text.lower()}"

            if any(word in combined for word in [
                "spectrogram",
                "sonogram",
                "waveform",
                "graph",
                "graphed song"
            ]):
                spectrogram = urljoin(species["url"], img["src"])
                break

        # skip if nothing useful found
        if not spectrogram:
            continue

        # attempt to extract temperature from description
        temp = None
        if "°" in text:
            i = text.find("°")
            temp = text[max(0, i - 5): i + 1].strip()

        # attempt to extraction location from description
        loc = "No location found"

        if "from" in text:
            start = text.find("from") + 5
            end = text.find("°") if "°" in text else len(text)
            loc = text[start:end]

        elif "in" in text:
            start = text.find("in") + 3
            end = text.find("°") if "°" in text else len(text)
            loc = text[start:end]

        loc = loc.strip(" ,;.")

        # put all pieces of data in grouped_data
        grouped_data.append({
            "Species": species_name,
            "URL": species["url"],
            "Spectrogram": spectrogram,
            "Audio": audio,
            "Description": text,
            "Temperature": temp,
            "Location": loc,
            "Map": map_large
        })

    time.sleep(random.uniform(1, 2))

In [34]:
cricket_df = pd.DataFrame(grouped_data)

In [35]:
cricket_df.columns = ['Species', 'URL', 'Spectrogram', 'Audio_Link', 'Description of Whole Audio File', 'Temperature (°C)', 'Location', 'Map']

In [36]:
cricket_df.head()

,Species,URL,Spectrogram,Audio_Link,Description of Whole Audio File,Temperature (°C),Location,Map
0,Gryllotalpa gryllotalpa,https://orthsoc.org/sina/363a.htm,https://orthsoc.org/sina/363ss2.jpg,https://orthsoc.org/sina/media/363ss2.mp3,This sound spectrogram is a 2 s excerpt of the 19 s audio file accesssible above. The excerpt begins at 2 s.,None,at 2 s,https://orthsoc.org/sina/363mc.gif
1,Gryllotalpa major,https://orthsoc.org/sina/361a.htm,https://orthsoc.org/sina/361ss2.gif,https://orthsoc.org/sina/media/361ss2.mp3,This sound spectrogram is a 2 s excerpt of the 20 s audio file accesssible above.,None,No location found,https://orthsoc.org/sina/361mc.gif
2,Neocurtilla hexadactyla,https://orthsoc.org/sina/351a.htm,https://orthsoc.org/sina/351ss2.gif,https://orthsoc.org/sina/media/351ss2.mp3,This spectrogram is a 2 s excerpt of the 16 s audio file accessible above.,None,No location found,https://orthsoc.org/sina/351mc.gif
3,Neoscapteriscus borellii,https://orthsoc.org/sina/341a.htm,https://orthsoc.org/sina/341ss2.gif,https://orthsoc.org/sina/media/341ss2.mp3,This spectrogram is a 2 s excerpt of the 20 s audio file accessible above.,None,No location found,https://orthsoc.org/sina/341mc.gif
4,Neoscapteriscus vicinus,https://orthsoc.org/sina/342a.htm,https://orthsoc.org/sina/342ss2.gif,https://orthsoc.org/sina/media/342ss2.mp3,This spectrogram is a 1 s excerpt of the 22 s audio file accessible above. Differences among pulses are a result of limitations of the software used to produce the spectrogram. Click on spectrogram to expand its spectrographic image.,None,No location found,https://orthsoc.org/sina/342mc.gif

## Katydid Dataframe

In [37]:
# define for reference later
url = 'https://orthsoc.org/sina/katylist.htm'

In [38]:
# get code for katydid webpage
response = requests.get(url, headers = headers)
katydid_soup = BeautifulSoup(response.text, 'html.parser')

In [39]:
# retrieve species names and urls and store them in species_list
katydid_species_list = []
for species in katydid_soup.find_all("h3", class_="species"):
    a_tag = species.find("a")
    if a_tag:
        species_name = a_tag.get_text(strip = True)
        species_url = urljoin("https://orthsoc.org/sina/", a_tag["href"])
        katydid_species_list.append({"species": species_name, "url": species_url})

In [40]:
grouped_data = []
session = requests.Session()
session.headers.update(headers)

for species in katydid_species_list:
    r = session.get(species["url"], timeout=15)
    r.encoding = r.apparent_encoding
    soup = BeautifulSoup(r.text, "html.parser")

    species_name = species["species"]

    # finding range map of species (if possible)
    map_large = None
    map_figure = soup.find("table", class_="images")

    if map_figure:
        map_link = map_figure.find("a", href=True)
        if map_link:
            href = map_link["href"]

            match = re.search(r"(\d+)m\.htm", href, re.I)
            if match:
                code = match.group(1)
                href = f"{code}mc.gif"
                map_large = urljoin(species["url"], href)

    if not map_large:
        for row in soup.find_all("tr"):
            caps = row.find_all("td", class_="captions")
            for idx, cap in enumerate(caps):
                if "map" in cap.get_text(" ", strip=True).lower():
                    prev = row.find_previous_sibling("tr")
                    if not prev:
                        continue

                    imgs = prev.find_all("td", class_="images")
                    if idx >= len(imgs):
                        continue

                    link = imgs[idx].find("a", href=True)
                    if not link:
                        continue

                    href = link["href"]
                    match = re.search(r"(\d+)m\.htm", href, re.I)
                    if match:
                        code = match.group(1)
                        href = f"{code}mc.gif"
                        map_large = urljoin(species["url"], href)
                    break
            if map_large:
                break

    recording_blocks = soup.find_all(
        "div",
        class_=lambda x: x and "recording" in x
    )

    for rec in recording_blocks:

        text = rec.get_text(" ", strip=True)

        # find audio file
        audio = None
        audio_tag = rec.find("audio")
        if audio_tag:
            source = audio_tag.find("source", src=True)
            if source:
                audio = urljoin(species["url"], source["src"])

        # find spectrogram
        spectrogram = None

        for img in rec.find_all("img", src=True):
            src = img["src"].lower()
            alt = (img.get("alt") or "").lower()

            combined = f"{src} {alt} {text.lower()}"

            if any(word in combined for word in [
                "spectrogram",
                "sonogram",
                "waveform",
                "graph",
                "graphed song"
            ]):
                spectrogram = urljoin(species["url"], img["src"])
                break

        # skip if nothing useful found
        if not spectrogram:
            continue

        # attempt to extract temperature from description
        temp = None
        if "°" in text:
            i = text.find("°")
            temp = text[max(0, i - 5): i + 1].strip()

        # attempt to extraction location from description
        loc = "No location found"

        if "from" in text:
            start = text.find("from") + 5
            end = text.find("°") if "°" in text else len(text)
            loc = text[start:end]

        elif "in" in text:
            start = text.find("in") + 3
            end = text.find("°") if "°" in text else len(text)
            loc = text[start:end]

        loc = loc.strip(" ,;.")

        # put all pieces of data in grouped_data
        grouped_data.append({
            "Species": species_name,
            "URL": species["url"],
            "Spectrogram": spectrogram,
            "Audio": audio,
            "Description": text,
            "Temperature": temp,
            "Location": loc,
            "Map": map_large
        })

    time.sleep(random.uniform(1, 2))

In [41]:
katydid_df = pd.DataFrame(grouped_data)

In [42]:
katydid_df.columns = ['Species', 'URL', 'Spectrogram', 'Audio_Link', 'Description', 'Temperature (°C)', 'Location', 'Map']

In [43]:
katydid_df.head()

,Species,URL,Spectrogram,Audio_Link,Description,Temperature (°C),Location,Map
0,Cyphoderris buckelli,https://orthsoc.org/sina/337a.htm,https://orthsoc.org/sina/337ss2.gif,https://orthsoc.org/sina/media/337ss2.mp3,This waveform is a 2 s excerpt of the 10 s audio file accessible above (slowed to half speed). Click on waveform to expand last 0.25 s of waveform.,None,No location found,https://orthsoc.org/sina/337mc.gif
1,Conocephalus aigialus,https://orthsoc.org/sina/230a.htm,https://orthsoc.org/sina/230ss2.gif,https://orthsoc.org/sina/media/230ss2.mp3,This waveform is a 5 s excerpt of the 20 s audio file accessible above. Click on waveform to expand last 0.5 s of song.,None,No location found,https://orthsoc.org/sina/230mc.gif
2,Conocephalus allardi,https://orthsoc.org/sina/220a.htm,https://orthsoc.org/sina/220ss2.gif,https://orthsoc.org/sina/media/220ss2.mp3,This waveform is a 5 s excerpt of the 70 s audio file accessible above. Click on waveform to expand 0.5 s of the 5 s song.,None,No location found,https://orthsoc.org/sina/220mc.gif
3,Conocephalus attenuatus,https://orthsoc.org/sina/228a.htm,https://orthsoc.org/sina/228ss2.gif,https://orthsoc.org/sina/media/228ss2.mp3,This waveform is a 5 s excerpt of the 22 s audio file accessible above. Click on waveform to expand last 0.5 s of song.,None,No location found,https://orthsoc.org/sina/228mc.gif
4,Conocephalus brevipennis,https://orthsoc.org/sina/234a.htm,https://orthsoc.org/sina/234ss2.gif,https://orthsoc.org/sina/media/234ss2.mp3,This waveform is a 5 s excerpt of the 20 s audio file accessible above. Click on waveform to expand 0.5 s of buzz.,None,No location found,https://orthsoc.org/sina/234mc.gif

## Frog Dataframe

In [44]:
# extract the data from different pages by looping over all frog pages in the API
page_num = 1
base_url = f'https://xeno-canto.org/api/3/recordings?query=grp:frogs&page={page_num}&key=18a98cdc0e5e1df2c91e00a17f4bfcf89cd501b6'
recordings = []
response = requests.get(base_url)
data = response.json()
recordings.extend(data["recordings"])
for n in range(2,58):
    page_num = n
    response = requests.get(base_url)
    data = response.json()
    recordings.extend(data["recordings"])
    time.sleep(random.uniform(2,4))

In [45]:
# flatten nested data
df = pd.json_normalize(recordings)

In [46]:
# extract useful columns
frog_df = df[['gen', 'sp', 'cnt', 'loc', 'lat', 'lon', 'type', 'file', 'sono.med']]

In [47]:
# rename extracted columns
frog_df.columns = ['Genus', 'Species', 'Country', 'Location', 'Latitude', 'Longitude', 'Call Type', 'File', 'Spectrogram']

In [48]:
frog_df.head()

,Genus,Species,Country,Location,Latitude,Longitude,Call Type,File,Spectrogram
0,Hyla,meridionalis,France,"Arrondissement de Marseille (near Marseille), Bouches-du-Rhone, Provence-Alpes-Côte d'Azur",43.2755,5.48,territorial call,https://xeno-canto.org/1139790/download,https://xeno-canto.org/sounds/spectrograms/YEUMVPMDCG/1139790/grey-medium.png
1,Hyla,meridionalis,France,"Arrondissement de Marseille (near Marseille), Bouches-du-Rhone, Provence-Alpes-Côte d'Azur",43.2755,5.48,territorial call,https://xeno-canto.org/1139789/download,https://xeno-canto.org/sounds/spectrograms/YEUMVPMDCG/1139789/grey-medium.png
2,Hyla,meridionalis,France,"Arrondissement de Marseille (near Marseille), Bouches-du-Rhone, Provence-Alpes-Côte d'Azur",43.2755,5.48,territorial call,https://xeno-canto.org/1139788/download,https://xeno-canto.org/sounds/spectrograms/YEUMVPMDCG/1139788/grey-medium.png
3,Phyllomedusa,distincta,Brazil,"Estação Ecológica Juréia-Itatins, Peruíbe, São Paulo",-24.3893,-47.0188,advertisement call,https://xeno-canto.org/1139730/download,https://xeno-canto.org/sounds/spectrograms/YOXWKYFZAP/1139730/grey-medium.png
4,Odontophrynus,asper,Paraguay,"Potrero Jakarey, Valenzuela, Cordillera",-25.6313,-56.8743,,https://xeno-canto.org/1139604/download,https://xeno-canto.org/sounds/spectrograms/VALRNZCFXZ/1139604/grey-medium.png

## Downloading Files

### Crickets

In [49]:
def get_file_id(url):
    return os.path.splitext(os.path.basename(str(url)))[0]

In [50]:
base_folder = Path.home() / "Discrete_Signals"

In [51]:
base_folder = Path.home() / "Discrete_Signals"

group_folders = {
    "crickets": base_folder / "Crickets",
    "katydids": base_folder / "Katydids",
    "frogs": base_folder / "Frogs"
}

for folder in group_folders.values():
    folder.mkdir(parents=True, exist_ok=True)

In [52]:
def download_file(url, path, headers):
    try:
        r = requests.get(url, headers=headers, timeout=20)
        r.raise_for_status()

        content_type = r.headers.get("Content-Type", "").lower()

        if "text/html" in content_type:
            print(f"Skipping HTML page masquerading as asset: {url}")
            return

        # making sure it's not an error page
        if r.content.startswith(b"<!DOCTYPE") or r.content.startswith(b"<html"):
            print(f"Skipping text/html payload for: {url}")
            return

        with open(path, "wb") as f:
            f.write(r.content)

    except Exception as e:
        print(f"Download failed: {url}")
        print(e)

In [53]:
for idx, row in cricket_df.iterrows():
    spectrogram_url = row.get("Spectrogram")
    audio_url = row.get("Audio_Link")
    map_url = row.get("Map")

    if pd.isna(spectrogram_url) and pd.isna(audio_url) and pd.isna(map_url):
        continue

    species = str(row["Species"]).replace(" ", "_")

    # create species subfolder inside Crickets
    species_folder = group_folders["crickets"] / species
    species_folder.mkdir(parents=True, exist_ok=True)

    spec_id = None

    if pd.notna(spectrogram_url) and spectrogram_url:
        ext = os.path.splitext(spectrogram_url)[1].lower()
        if ext not in [".jpg", ".jpeg", ".png", ".gif", ".webp"]:
            ext = ".gif"

        spec_id = get_file_id(spectrogram_url)
        spec_path = species_folder / f"{species}_spectrogram_{spec_id}{ext}"
        download_file(spectrogram_url, spec_path, headers)

    if pd.notna(audio_url):
        audio_url = str(audio_url).strip()
        ext = os.path.splitext(audio_url)[1].lower()
        if ext not in [".mp3", ".wav", ".ogg"]:
            ext = ".wav"

        audio_id = spec_id or get_file_id(audio_url)
        audio_path = species_folder / f"{species}_audio_{audio_id}{ext}"

        try:
            r = session.get(audio_url, timeout=20)
            r.raise_for_status()

            with open(audio_path, "wb") as f:
                f.write(r.content)

        except Exception as e:
            print(f"Error downloading audio {audio_url}")
            print(e)

    if pd.notna(map_url) and map_url:
        ext = os.path.splitext(map_url)[1].lower()
        if ext not in [".gif", ".jpg", ".jpeg", ".png", ".webp"]:
            ext = ".gif"

        map_id = get_file_id(map_url)
        map_path = species_folder / f"{species}_map_{map_id}{ext}"
        download_file(map_url, map_path, headers)

Download failed: https://orthsoc.org/sina/469mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/469mc.gif
Download failed: https://orthsoc.org/sina/469mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/469mc.gif
Download failed: https://orthsoc.org/sina/469mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/469mc.gif
Download failed: https://orthsoc.org/sina/721mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/721mc.gif
Download failed: https://orthsoc.org/sina/721mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/721mc.gif
Download failed: https://orthsoc.org/sina/722mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/722mc.gif
Download failed: https://orthsoc.org/sina/722mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/722mc.gif
Download failed: https://orthsoc.org/sina/723mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/723mc.gif
Download failed: https://orthsoc.org/sina/723mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/723mc.gif
Download failed: https://orthsoc.org/sina/724mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/724mc.gif
Download failed: https://orthsoc.org/sina/724mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/724mc.gif
Download failed: https://orthsoc.org/sina/725mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/725mc.gif
Download failed: https://orthsoc.org/sina/725mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/725mc.gif
Download failed: https://orthsoc.org/sina/726mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/726mc.gif
Download failed: https://orthsoc.org/sina/726mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/726mc.gif
Download failed: https://orthsoc.org/sina/727mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/727mc.gif
Download failed: https://orthsoc.org/sina/727mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/727mc.gif
Download failed: https://orthsoc.org/sina/499mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/499mc.gif
Download failed: https://orthsoc.org/sina/499mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/499mc.gif
Download failed: https://orthsoc.org/sina/499mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/499mc.gif
Download failed: https://orthsoc.org/sina/499mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/499mc.gif
Download failed: https://orthsoc.org/sina/728mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/728mc.gif
Download failed: https://orthsoc.org/sina/728mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/728mc.gif
Download failed: https://orthsoc.org/sina/729mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/729mc.gif
Download failed: https://orthsoc.org/sina/729mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/729mc.gif
Download failed: https://orthsoc.org/sina/730mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/730mc.gif
Download failed: https://orthsoc.org/sina/730mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/730mc.gif
Download failed: https://orthsoc.org/sina/731mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/731mc.gif
Download failed: https://orthsoc.org/sina/731mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/731mc.gif
Download failed: https://orthsoc.org/sina/732mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/732mc.gif
Download failed: https://orthsoc.org/sina/732mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/732mc.gif
Download failed: https://orthsoc.org/sina/733mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/733mc.gif
Download failed: https://orthsoc.org/sina/733mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/733mc.gif
Download failed: https://orthsoc.org/sina/733mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/733mc.gif
Download failed: https://orthsoc.org/sina/733mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/733mc.gif
Download failed: https://orthsoc.org/sina/734mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/734mc.gif
Download failed: https://orthsoc.org/sina/734mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/734mc.gif
Download failed: https://orthsoc.org/sina/735mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/735mc.gif
Download failed: https://orthsoc.org/sina/735mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/735mc.gif
Download failed: https://orthsoc.org/sina/736mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/736mc.gif
Download failed: https://orthsoc.org/sina/736mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/736mc.gif
Download failed: https://orthsoc.org/sina/737mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/737mc.gif
Download failed: https://orthsoc.org/sina/737mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/737mc.gif
Download failed: https://orthsoc.org/sina/738mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/738mc.gif
Download failed: https://orthsoc.org/sina/738mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/738mc.gif
Download failed: https://orthsoc.org/sina/549mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/549mc.gif
Download failed: https://orthsoc.org/sina/549mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/549mc.gif
Download failed: https://orthsoc.org/sina/549mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/549mc.gif
Download failed: https://orthsoc.org/sina/548mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/548mc.gif
Download failed: https://orthsoc.org/sina/548mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/548mc.gif
Download failed: https://orthsoc.org/sina/575mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/575mc.gif
Download failed: https://orthsoc.org/sina/575mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/575mc.gif
Download failed: https://orthsoc.org/sina/598mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/598mc.gif
Download failed: https://orthsoc.org/sina/598mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/598mc.gif
Download failed: https://orthsoc.org/sina/598mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/598mc.gif
Download failed: https://orthsoc.org/sina/573mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/573mc.gif
Download failed: https://orthsoc.org/sina/636mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/636mc.gif
Download failed: https://orthsoc.org/sina/637mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/637mc.gif

### Katydids

In [54]:
for idx, row in katydid_df.iterrows():
    spectrogram_url = row.get("Spectrogram")
    audio_url = row.get("Audio_Link")
    map_url = row.get("Map")

    if pd.isna(spectrogram_url) and pd.isna(audio_url) and pd.isna(map_url):
        continue

    species = str(row["Species"]).replace(" ", "_")

    species_folder = group_folders["katydids"] / species
    species_folder.mkdir(parents=True, exist_ok=True)

    spec_id = None

    if pd.notna(spectrogram_url) and spectrogram_url:
        ext = os.path.splitext(spectrogram_url)[1].lower()
        if ext not in [".jpg", ".jpeg", ".png", ".gif", ".webp"]:
            ext = ".gif"

        spec_id = get_file_id(spectrogram_url)
        spec_path = species_folder / f"{species}_spectrogram_{spec_id}{ext}"
        download_file(spectrogram_url, spec_path, headers)

    if pd.notna(audio_url):
        audio_url = str(audio_url).strip()
        ext = os.path.splitext(audio_url)[1].lower()
        if ext not in [".mp3", ".wav", ".ogg"]:
            ext = ".wav"

        audio_id = spec_id or get_file_id(audio_url)
        audio_path = species_folder / f"{species}_audio_{audio_id}{ext}"

        try:
            r = session.get(audio_url, timeout=20)
            r.raise_for_status()

            with open(audio_path, "wb") as f:
                f.write(r.content)

        except Exception as e:
            print(f"Error downloading audio {audio_url}")
            print(e)

    if pd.notna(map_url) and map_url:
        ext = os.path.splitext(map_url)[1].lower()
        if ext not in [".gif", ".jpg", ".jpeg", ".png", ".webp"]:
            ext = ".gif"

        map_id = get_file_id(map_url)
        map_path = species_folder / f"{species}_map_{map_id}{ext}"
        download_file(map_url, map_path, headers)

Download failed: https://orthsoc.org/sina/235mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/235mc.gif
Download failed: https://orthsoc.org/sina/801mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/801mc.gif
Download failed: https://orthsoc.org/sina/801mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/801mc.gif
Download failed: https://orthsoc.org/sina/802mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/802mc.gif
Download failed: https://orthsoc.org/sina/802mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/802mc.gif
Download failed: https://orthsoc.org/sina/803mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/803mc.gif
Download failed: https://orthsoc.org/sina/803mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/803mc.gif
Download failed: https://orthsoc.org/sina/804mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/804mc.gif
Download failed: https://orthsoc.org/sina/804mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/804mc.gif
Download failed: https://orthsoc.org/sina/805mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/805mc.gif
Download failed: https://orthsoc.org/sina/805mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/805mc.gif
Download failed: https://orthsoc.org/sina/806mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/806mc.gif
Download failed: https://orthsoc.org/sina/806mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/806mc.gif
Download failed: https://orthsoc.org/sina/807mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/807mc.gif
Download failed: https://orthsoc.org/sina/807mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/807mc.gif
Download failed: https://orthsoc.org/sina/808mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/808mc.gif
Download failed: https://orthsoc.org/sina/808mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/808mc.gif
Download failed: https://orthsoc.org/sina/809mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/809mc.gif
Download failed: https://orthsoc.org/sina/809mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/809mc.gif
Download failed: https://orthsoc.org/sina/810mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/810mc.gif
Download failed: https://orthsoc.org/sina/810mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/810mc.gif
Download failed: https://orthsoc.org/sina/811mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/811mc.gif
Download failed: https://orthsoc.org/sina/811mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/811mc.gif
Download failed: https://orthsoc.org/sina/812mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/812mc.gif
Download failed: https://orthsoc.org/sina/812mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/812mc.gif
Download failed: https://orthsoc.org/sina/813mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/813mc.gif
Download failed: https://orthsoc.org/sina/813mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/813mc.gif
Download failed: https://orthsoc.org/sina/814mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/814mc.gif
Download failed: https://orthsoc.org/sina/814mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/814mc.gif
Download failed: https://orthsoc.org/sina/815mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/815mc.gif
Download failed: https://orthsoc.org/sina/815mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/815mc.gif
Download failed: https://orthsoc.org/sina/816mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/816mc.gif
Download failed: https://orthsoc.org/sina/816mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/816mc.gif
Download failed: https://orthsoc.org/sina/817mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/817mc.gif
Download failed: https://orthsoc.org/sina/817mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/817mc.gif
Download failed: https://orthsoc.org/sina/818mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/818mc.gif
Download failed: https://orthsoc.org/sina/818mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/818mc.gif
Download failed: https://orthsoc.org/sina/819mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/819mc.gif
Download failed: https://orthsoc.org/sina/819mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/819mc.gif
Download failed: https://orthsoc.org/sina/820mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/820mc.gif
Download failed: https://orthsoc.org/sina/820mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/820mc.gif
Error downloading audio https://orthsoc.org/sina/media306ss/.mp3
404 Client Error: Not Found for url: https://orthsoc.org/sina/media306ss/.mp3
Error downloading audio https://orthsoc.org/sina/media/297ss2d297ss2d.mp3
404 Client Error: Not Found for url: https://orthsoc.org/sina/media/297ss2d297ss2d.mp3
Download failed: https://orthsoc.org/sina/741mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/741mc.gif
Download failed: https://orthsoc.org/sina/742mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/742mc.gif
Download failed: https://orthsoc.org/sina/743mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/743mc.gif
Download failed: https://orthsoc.org/sina/744mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/744mc.gif
Download failed: https://orthsoc.org/sina/745mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/745mc.gif
Download failed: https://orthsoc.org/sina/746mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/746mc.gif
Download failed: https://orthsoc.org/sina/747mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/747mc.gif
Download failed: https://orthsoc.org/sina/748mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/748mc.gif
Download failed: https://orthsoc.org/sina/149mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/149mc.gif
Download failed: https://orthsoc.org/sina/750mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/750mc.gif
Download failed: https://orthsoc.org/sina/751mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/751mc.gif
Download failed: https://orthsoc.org/sina/752mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/752mc.gif
Download failed: https://orthsoc.org/sina/753mc.gif
404 Client Error: Not Found for url: https://orthsoc.org/sina/753mc.gif
Error downloading audio https://orthsoc.org/sina/media/314ssjclc.mp3
404 Client Error: Not Found for url: https://orthsoc.org/sina/media/314ssjclc.mp3

### Frogs

In [55]:
def get_id(url):
    return os.path.splitext(os.path.basename(url))[0]

def safe_download(session, url, path):
    if path.exists():
        return

    r = session.get(url, timeout=20)
    if r.status_code == 200:
        with open(path, "wb") as f:
            f.write(r.content)
    else:
        print(f"Failed ({r.status_code}): {url}")

In [56]:
def download_frogs(frog_df, base_folder, headers):
    frog_root = base_folder / "Frogs"
    session = requests.Session()
    session.headers.update(headers)
    n = 1
    for idx, row in frog_df.iterrows():

        genus = str(row["Genus"])
        species = str(row["Species"]).strip("'")
        species_name = f"{genus}_{species}"

        audio_url = row.get("File")
        spectrogram_url = row.get("Spectrogram")

        # skip empty rows
        if pd.isna(audio_url) and pd.isna(spectrogram_url):
            continue

        # create folder
        species_folder = frog_root / species_name
        species_folder.mkdir(parents=True, exist_ok=True)

        if pd.notna(audio_url):
            ext = os.path.splitext(str(audio_url))[1].lower()
            if ext not in [".mp3", ".wav", ".ogg"]:
                ext = ".mp3"

            audio_id = get_file_id(audio_url)
            audio_path = species_folder / f"{species}_audio_{audio_id}{ext}"

            try:
                if not audio_path.exists():
                    r = session.get(audio_url, timeout=20)
                    if r.status_code == 200:
                        with open(audio_path, "wb") as f:
                            f.write(r.content)
                    else:
                        print(f"Audio failed ({r.status_code}): {audio_url}")
            except Exception as e:
                print(f"Error downloading audio: {audio_url}")
                print(e)
                
        if pd.notna(spectrogram_url):
            ext = os.path.splitext(str(spectrogram_url))[1].lower()
            if ext not in [".jpg", ".jpeg", ".png", ".gif", ".webp"]:
                ext = ".png"

            spec_id = get_file_id(spectrogram_url)
            spec_path = species_folder / f"{species}_spectrogram_{spec_id}{ext}"

            try:
                if not spec_path.exists():
                    r = session.get(spectrogram_url, timeout=20)
                    if r.status_code == 200:
                        with open(spec_path, "wb") as f:
                            f.write(r.content)
                    else:
                        print(f"Spectrogram failed ({r.status_code}): {spectrogram_url}")
            except Exception as e:
                print(f"Error downloading spectrogram: {spectrogram_url}")
                print(e)

        n += 1
        print(f'{species_name} downloaded, {n*100/851}% completed')
        time.sleep(random.uniform(1,2))

In [57]:
download_frogs(frog_df, base_folder, headers)

Hyla_meridionalis downloaded, 0.23501762632197415% completed
Hyla_meridionalis downloaded, 0.3525264394829612% completed
Hyla_meridionalis downloaded, 0.4700352526439483% completed
Phyllomedusa_distincta downloaded, 0.5875440658049353% completed
Odontophrynus_asper downloaded, 0.7050528789659224% completed
Pelophylax_esculentus downloaded, 0.8225616921269095% completed
Melanophryniscus_fulvoguttatus downloaded, 0.9400705052878966% completed
Hylarana_baramica downloaded, 1.0575793184488838% completed
Pelophylax_ridibundus downloaded, 1.1750881316098707% completed
Pelophylax_ridibundus downloaded, 1.2925969447708578% completed
Pelophylax_ridibundus downloaded, 1.4101057579318448% completed
Hyla_arborea downloaded, 1.527614571092832% completed
Hyla_arborea downloaded, 1.645123384253819% completed
Hyla_arborea downloaded, 1.762632197414806% completed
Bombina_bombina downloaded, 1.8801410105757932% completed
Eleutherodactylus_cystignathoides downloaded, 1.9976498237367804% completed
Strauchbufo_raddei downloaded, 2.1151586368977675% completed
Smilisca_baudinii downloaded, 2.2326674500587544% completed
Pelophylax_ridibundus downloaded, 2.3501762632197414% completed
Hyla_arborea downloaded, 2.4676850763807288% completed
Hyla_arborea downloaded, 2.5851938895417157% completed
Bufotes_viridis downloaded, 2.7027027027027026% completed
Bufotes_viridis downloaded, 2.8202115158636896% completed
Bombina_bombina downloaded, 2.937720329024677% completed
Heleioporus_australiacus downloaded, 3.055229142185664% completed
Ischnocnema_guentheri downloaded, 3.172737955346651% completed
Rana_temporaria downloaded, 3.290246768507638% completed
Rana_arvalis downloaded, 3.407755581668625% completed
Rana_arvalis downloaded, 3.525264394829612% completed
Rana_temporaria downloaded, 3.6427732079905994% completed
Hyla_arborea downloaded, 3.7602820211515864% completed
Pelophylax_cypriensis downloaded, 3.8777908343125733% completed
Pelophylax_cypriensis downloaded, 3.9952996474735607% completed
Allophryne_resplendens downloaded, 4.112808460634548% completed
Platymantis_mimulus downloaded, 4.230317273795535% completed
Hyla_arborea downloaded, 4.3478260869565215% completed
Pelophylax_ridibundus downloaded, 4.465334900117509% completed
Kurixalus_naso downloaded, 4.582843713278496% completed
Boana_lanciformis downloaded, 4.700352526439483% completed
Bombina_bombina downloaded, 4.81786133960047% completed
Hyla_arborea downloaded, 4.9353701527614575% completed
Pelobates_fuscus downloaded, 5.052878965922444% completed
Pristimantis_bogotensis downloaded, 5.170387779083431% completed
Hylarana_guentheri downloaded, 5.287896592244419% completed
Hylodes_phyllodes downloaded, 5.405405405405405% completed
Hylarana_guentheri downloaded, 5.522914218566393% completed
Boana_wavrini downloaded, 5.640423031727379% completed
Dendropsophus_microcephalus downloaded, 5.7579318448883665% completed
Pristimantis_myersi downloaded, 5.875440658049354% completed
Gastrotheca_orophylax downloaded, 5.99294947121034% completed
Trachycephalus_resinifictrix downloaded, 6.110458284371328% completed
Leptodactylus_colombiensis downloaded, 6.227967097532315% completed
Epidalea_calamita downloaded, 6.345475910693302% completed
Pelophylax_ridibundus downloaded, 6.462984723854289% completed
Bombina_bombina downloaded, 6.580493537015276% completed
Hyla_arborea downloaded, 6.698002350176263% completed
Epidalea_calamita downloaded, 6.81551116333725% completed
Epidalea_calamita downloaded, 6.933019976498238% completed
Adenomera_hylaedactyla downloaded, 7.050528789659224% completed
Pelophylax_ridibundus downloaded, 7.1680376028202115% completed
Pelophylax_ridibundus downloaded, 7.285546415981199% completed
Pelophylax_ridibundus downloaded, 7.403055229142185% completed
Pelophylax_ridibundus downloaded, 7.520564042303173% completed
Pelophylax_ridibundus downloaded, 7.63807285546416% completed
Pelophylax_ridibundus downloaded, 7.755581668625147% completed
Pelophylax_ridibundus downloaded, 7.873090481786134% completed
Pelophylax_ridibundus downloaded, 7.990599294947121% completed
Pelophylax_ridibundus downloaded, 8.108108108108109% completed
Pelophylax_ridibundus downloaded, 8.225616921269095% completed
Pelophylax_ridibundus downloaded, 8.343125734430082% completed
Pelophylax_ridibundus downloaded, 8.46063454759107% completed
Pelophylax_ridibundus downloaded, 8.578143360752057% completed
Pelophylax_ridibundus downloaded, 8.695652173913043% completed
Pelophylax_ridibundus downloaded, 8.813160987074031% completed
Pelophylax_grafi downloaded, 8.930669800235018% completed
Pelophylax_grafi downloaded, 9.048178613396004% completed
Pelophylax_grafi downloaded, 9.165687426556993% completed
Pelophylax_grafi downloaded, 9.283196239717979% completed
Pelophylax_esculentus downloaded, 9.400705052878966% completed
Pelophylax_perezi downloaded, 9.518213866039954% completed
Pelophylax_perezi downloaded, 9.63572267920094% completed
Pelophylax_perezi downloaded, 9.753231492361927% completed
Pelophylax_perezi downloaded, 9.870740305522915% completed
Pelophylax_perezi downloaded, 9.988249118683902% completed
Pelophylax_perezi downloaded, 10.105757931844888% completed
Pelophylax_kurtmuelleri downloaded, 10.223266745005876% completed
Pelophylax_kurtmuelleri downloaded, 10.340775558166863% completed
Rhinella_marina downloaded, 10.45828437132785% completed
Epidalea_calamita downloaded, 10.575793184488838% completed
Hyla_intermedia downloaded, 10.693301997649824% completed
Rhinella_horribilis downloaded, 10.81081081081081% completed
Epidalea_calamita downloaded, 10.928319623971797% completed
Leptodactylus_pentadactylus downloaded, 11.045828437132785% completed
Litoria_peronii downloaded, 11.163337250293772% completed
Pristimantis_frater downloaded, 11.280846063454758% completed
Pristimantis_savagei downloaded, 11.398354876615747% completed
Hyla_arborea downloaded, 11.515863689776733% completed
Hyla_arborea downloaded, 11.63337250293772% completed
Bombina_bombina downloaded, 11.750881316098708% completed
Bombina_bombina downloaded, 11.868390129259694% completed
Hyla_meridionalis downloaded, 11.98589894242068% completed
Hyla_meridionalis downloaded, 12.103407755581669% completed
Hyla_meridionalis downloaded, 12.220916568742656% completed
Phyllomedusa_distincta downloaded, 12.338425381903642% completed
Odontophrynus_asper downloaded, 12.45593419506463% completed
Pelophylax_esculentus downloaded, 12.573443008225617% completed
Melanophryniscus_fulvoguttatus downloaded, 12.690951821386603% completed
Hylarana_baramica downloaded, 12.808460634547592% completed
Pelophylax_ridibundus downloaded, 12.925969447708578% completed
Pelophylax_ridibundus downloaded, 13.043478260869565% completed
Pelophylax_ridibundus downloaded, 13.160987074030553% completed
Hyla_arborea downloaded, 13.27849588719154% completed
Hyla_arborea downloaded, 13.396004700352526% completed
Hyla_arborea downloaded, 13.513513513513514% completed
Bombina_bombina downloaded, 13.6310223266745% completed
Eleutherodactylus_cystignathoides downloaded, 13.748531139835487% completed
Strauchbufo_raddei downloaded, 13.866039952996475% completed
Smilisca_baudinii downloaded, 13.983548766157462% completed
Pelophylax_ridibundus downloaded, 14.101057579318448% completed
Hyla_arborea downloaded, 14.218566392479437% completed
Hyla_arborea downloaded, 14.336075205640423% completed
Bufotes_viridis downloaded, 14.45358401880141% completed
Bufotes_viridis downloaded, 14.571092831962398% completed
Bombina_bombina downloaded, 14.688601645123384% completed
Heleioporus_australiacus downloaded, 14.80611045828437% completed
Ischnocnema_guentheri downloaded, 14.923619271445359% completed
Rana_temporaria downloaded, 15.041128084606346% completed
Rana_arvalis downloaded, 15.158636897767332% completed
Rana_arvalis downloaded, 15.27614571092832% completed
Rana_temporaria downloaded, 15.393654524089307% completed
Hyla_arborea downloaded, 15.511163337250293% completed
Pelophylax_cypriensis downloaded, 15.628672150411282% completed
Pelophylax_cypriensis downloaded, 15.746180963572268% completed
Allophryne_resplendens downloaded, 15.863689776733255% completed
Platymantis_mimulus downloaded, 15.981198589894243% completed
Hyla_arborea downloaded, 16.09870740305523% completed
Pelophylax_ridibundus downloaded, 16.216216216216218% completed
Kurixalus_naso downloaded, 16.333725029377202% completed
Boana_lanciformis downloaded, 16.45123384253819% completed
Bombina_bombina downloaded, 16.56874265569918% completed
Hyla_arborea downloaded, 16.686251468860164% completed
Pelobates_fuscus downloaded, 16.803760282021152% completed
Pristimantis_bogotensis downloaded, 16.92126909518214% completed
Hylarana_guentheri downloaded, 17.038777908343125% completed
Hylodes_phyllodes downloaded, 17.156286721504113% completed
Hylarana_guentheri downloaded, 17.2737955346651% completed
Boana_wavrini downloaded, 17.391304347826086% completed
Dendropsophus_microcephalus downloaded, 17.508813160987074% completed
Pristimantis_myersi downloaded, 17.626321974148063% completed
Gastrotheca_orophylax downloaded, 17.743830787309047% completed
Trachycephalus_resinifictrix downloaded, 17.861339600470036% completed
Leptodactylus_colombiensis downloaded, 17.978848413631024% completed
Epidalea_calamita downloaded, 18.09635722679201% completed
Pelophylax_ridibundus downloaded, 18.213866039952997% completed
Bombina_bombina downloaded, 18.331374853113985% completed
Hyla_arborea downloaded, 18.44888366627497% completed
Epidalea_calamita downloaded, 18.566392479435958% completed
Epidalea_calamita downloaded, 18.683901292596946% completed
Adenomera_hylaedactyla downloaded, 18.80141010575793% completed
Pelophylax_ridibundus downloaded, 18.91891891891892% completed
Pelophylax_ridibundus downloaded, 19.036427732079908% completed
Pelophylax_ridibundus downloaded, 19.153936545240892% completed
Pelophylax_ridibundus downloaded, 19.27144535840188% completed
Pelophylax_ridibundus downloaded, 19.38895417156287% completed
Pelophylax_ridibundus downloaded, 19.506462984723854% completed
Pelophylax_ridibundus downloaded, 19.623971797884842% completed
Pelophylax_ridibundus downloaded, 19.74148061104583% completed
Pelophylax_ridibundus downloaded, 19.858989424206815% completed
Pelophylax_ridibundus downloaded, 19.976498237367803% completed
Pelophylax_ridibundus downloaded, 20.09400705052879% completed
Pelophylax_ridibundus downloaded, 20.211515863689776% completed
Pelophylax_ridibundus downloaded, 20.329024676850764% completed
Pelophylax_ridibundus downloaded, 20.446533490011753% completed
Pelophylax_ridibundus downloaded, 20.564042303172737% completed
Pelophylax_grafi downloaded, 20.681551116333726% completed
Pelophylax_grafi downloaded, 20.799059929494714% completed
Pelophylax_grafi downloaded, 20.9165687426557% completed
Pelophylax_grafi downloaded, 21.034077555816687% completed
Pelophylax_esculentus downloaded, 21.151586368977675% completed
Pelophylax_perezi downloaded, 21.26909518213866% completed
Pelophylax_perezi downloaded, 21.386603995299648% completed
Pelophylax_perezi downloaded, 21.504112808460633% completed
Pelophylax_perezi downloaded, 21.62162162162162% completed
Pelophylax_perezi downloaded, 21.73913043478261% completed
Pelophylax_perezi downloaded, 21.856639247943594% completed
Pelophylax_kurtmuelleri downloaded, 21.974148061104582% completed
Pelophylax_kurtmuelleri downloaded, 22.09165687426557% completed
Rhinella_marina downloaded, 22.209165687426555% completed
Epidalea_calamita downloaded, 22.326674500587544% completed
Hyla_intermedia downloaded, 22.444183313748532% completed
Rhinella_horribilis downloaded, 22.561692126909517% completed
Epidalea_calamita downloaded, 22.679200940070505% completed
Leptodactylus_pentadactylus downloaded, 22.796709753231493% completed
Litoria_peronii downloaded, 22.914218566392478% completed
Pristimantis_frater downloaded, 23.031727379553466% completed
Pristimantis_savagei downloaded, 23.149236192714454% completed
Hyla_arborea downloaded, 23.26674500587544% completed
Hyla_arborea downloaded, 23.384253819036427% completed
Bombina_bombina downloaded, 23.501762632197416% completed
Bombina_bombina downloaded, 23.6192714453584% completed
Hyla_meridionalis downloaded, 23.73678025851939% completed
Hyla_meridionalis downloaded, 23.854289071680377% completed
Hyla_meridionalis downloaded, 23.97179788484136% completed
Phyllomedusa_distincta downloaded, 24.08930669800235% completed
Odontophrynus_asper downloaded, 24.206815511163338% completed
Pelophylax_esculentus downloaded, 24.324324324324323% completed
Melanophryniscus_fulvoguttatus downloaded, 24.44183313748531% completed
Hylarana_baramica downloaded, 24.5593419506463% completed
Pelophylax_ridibundus downloaded, 24.676850763807284% completed
Pelophylax_ridibundus downloaded, 24.794359576968272% completed
Pelophylax_ridibundus downloaded, 24.91186839012926% completed
Hyla_arborea downloaded, 25.029377203290245% completed
Hyla_arborea downloaded, 25.146886016451234% completed
Hyla_arborea downloaded, 25.264394829612222% completed
Bombina_bombina downloaded, 25.381903642773207% completed
Eleutherodactylus_cystignathoides downloaded, 25.499412455934195% completed
Strauchbufo_raddei downloaded, 25.616921269095183% completed
Smilisca_baudinii downloaded, 25.734430082256168% completed
Pelophylax_ridibundus downloaded, 25.851938895417156% completed
Hyla_arborea downloaded, 25.969447708578144% completed
Hyla_arborea downloaded, 26.08695652173913% completed
Bufotes_viridis downloaded, 26.204465334900117% completed
Bufotes_viridis downloaded, 26.321974148061106% completed
Bombina_bombina downloaded, 26.43948296122209% completed
Heleioporus_australiacus downloaded, 26.55699177438308% completed
Ischnocnema_guentheri downloaded, 26.674500587544067% completed
Rana_temporaria downloaded, 26.79200940070505% completed
Rana_arvalis downloaded, 26.90951821386604% completed
Rana_arvalis downloaded, 27.027027027027028% completed
Rana_temporaria downloaded, 27.144535840188013% completed
Hyla_arborea downloaded, 27.262044653349% completed
Pelophylax_cypriensis downloaded, 27.37955346650999% completed
Pelophylax_cypriensis downloaded, 27.497062279670974% completed
Allophryne_resplendens downloaded, 27.614571092831962% completed
Platymantis_mimulus downloaded, 27.73207990599295% completed
Hyla_arborea downloaded, 27.849588719153935% completed
Pelophylax_ridibundus downloaded, 27.967097532314924% completed
Kurixalus_naso downloaded, 28.084606345475912% completed
Boana_lanciformis downloaded, 28.202115158636897% completed
Bombina_bombina downloaded, 28.319623971797885% completed
Hyla_arborea downloaded, 28.437132784958873% completed
Pelobates_fuscus downloaded, 28.554641598119858% completed
Pristimantis_bogotensis downloaded, 28.672150411280846% completed
Hylarana_guentheri downloaded, 28.789659224441834% completed
Hylodes_phyllodes downloaded, 28.90716803760282% completed
Hylarana_guentheri downloaded, 29.024676850763807% completed
Boana_wavrini downloaded, 29.142185663924796% completed
Dendropsophus_microcephalus downloaded, 29.25969447708578% completed
Pristimantis_myersi downloaded, 29.37720329024677% completed
Gastrotheca_orophylax downloaded, 29.494712103407757% completed
Trachycephalus_resinifictrix downloaded, 29.61222091656874% completed
Leptodactylus_colombiensis downloaded, 29.72972972972973% completed
Epidalea_calamita downloaded, 29.847238542890718% completed
Pelophylax_ridibundus downloaded, 29.964747356051703% completed
Bombina_bombina downloaded, 30.08225616921269% completed
Hyla_arborea downloaded, 30.19976498237368% completed
Epidalea_calamita downloaded, 30.317273795534664% completed
Epidalea_calamita downloaded, 30.434782608695652% completed
Adenomera_hylaedactyla downloaded, 30.55229142185664% completed
Pelophylax_ridibundus downloaded, 30.669800235017625% completed
Pelophylax_ridibundus downloaded, 30.787309048178614% completed
Pelophylax_ridibundus downloaded, 30.904817861339602% completed
Pelophylax_ridibundus downloaded, 31.022326674500587% completed
Pelophylax_ridibundus downloaded, 31.139835487661575% completed
Pelophylax_ridibundus downloaded, 31.257344300822563% completed
Pelophylax_ridibundus downloaded, 31.374853113983548% completed
Pelophylax_ridibundus downloaded, 31.492361927144536% completed
Pelophylax_ridibundus downloaded, 31.609870740305524% completed
Pelophylax_ridibundus downloaded, 31.72737955346651% completed
Pelophylax_ridibundus downloaded, 31.844888366627497% completed
Pelophylax_ridibundus downloaded, 31.962397179788486% completed
Pelophylax_ridibundus downloaded, 32.07990599294947% completed
Pelophylax_ridibundus downloaded, 32.19741480611046% completed
Pelophylax_ridibundus downloaded, 32.31492361927145% completed
Pelophylax_grafi downloaded, 32.432432432432435% completed
Pelophylax_grafi downloaded, 32.549941245593416% completed
Pelophylax_grafi downloaded, 32.667450058754405% completed
Pelophylax_grafi downloaded, 32.78495887191539% completed
Pelophylax_esculentus downloaded, 32.90246768507638% completed
Pelophylax_perezi downloaded, 33.01997649823737% completed
Pelophylax_perezi downloaded, 33.13748531139836% completed
Pelophylax_perezi downloaded, 33.25499412455934% completed
Pelophylax_perezi downloaded, 33.37250293772033% completed
Pelophylax_perezi downloaded, 33.490011750881315% completed
Pelophylax_perezi downloaded, 33.607520564042304% completed
Pelophylax_kurtmuelleri downloaded, 33.72502937720329% completed
Pelophylax_kurtmuelleri downloaded, 33.84253819036428% completed
Rhinella_marina downloaded, 33.96004700352526% completed
Epidalea_calamita downloaded, 34.07755581668625% completed
Hyla_intermedia downloaded, 34.19506462984724% completed
Rhinella_horribilis downloaded, 34.312573443008226% completed
Epidalea_calamita downloaded, 34.430082256169214% completed
Leptodactylus_pentadactylus downloaded, 34.5475910693302% completed
Litoria_peronii downloaded, 34.665099882491184% completed
Pristimantis_frater downloaded, 34.78260869565217% completed
Pristimantis_savagei downloaded, 34.90011750881316% completed
Hyla_arborea downloaded, 35.01762632197415% completed
Hyla_arborea downloaded, 35.13513513513514% completed
Bombina_bombina downloaded, 35.252643948296125% completed
Bombina_bombina downloaded, 35.370152761457106% completed
Hyla_meridionalis downloaded, 35.487661574618095% completed
Hyla_meridionalis downloaded, 35.60517038777908% completed
Hyla_meridionalis downloaded, 35.72267920094007% completed
Phyllomedusa_distincta downloaded, 35.84018801410106% completed
Odontophrynus_asper downloaded, 35.95769682726205% completed
Pelophylax_esculentus downloaded, 36.07520564042303% completed
Melanophryniscus_fulvoguttatus downloaded, 36.19271445358402% completed
Hylarana_baramica downloaded, 36.310223266745005% completed
Pelophylax_ridibundus downloaded, 36.427732079905994% completed
Pelophylax_ridibundus downloaded, 36.54524089306698% completed
Pelophylax_ridibundus downloaded, 36.66274970622797% completed
Hyla_arborea downloaded, 36.78025851938895% completed
Hyla_arborea downloaded, 36.89776733254994% completed
Hyla_arborea downloaded, 37.01527614571093% completed
Bombina_bombina downloaded, 37.132784958871916% completed
Eleutherodactylus_cystignathoides downloaded, 37.250293772032904% completed
Strauchbufo_raddei downloaded, 37.36780258519389% completed
Smilisca_baudinii downloaded, 37.485311398354874% completed
Pelophylax_ridibundus downloaded, 37.60282021151586% completed
Hyla_arborea downloaded, 37.72032902467685% completed
Hyla_arborea downloaded, 37.83783783783784% completed
Bufotes_viridis downloaded, 37.95534665099883% completed
Bufotes_viridis downloaded, 38.072855464159815% completed
Bombina_bombina downloaded, 38.190364277320796% completed
Heleioporus_australiacus downloaded, 38.307873090481785% completed
Ischnocnema_guentheri downloaded, 38.42538190364277% completed
Rana_temporaria downloaded, 38.54289071680376% completed
Rana_arvalis downloaded, 38.66039952996475% completed
Rana_arvalis downloaded, 38.77790834312574% completed